version: 2
updates:
- package-ecosystem: "github-actions"
  directory: "/"
  schedule:
    interval: "daily"
  commit-message:
    prefix: "GitHub Actions"
    include: "scope"
- package-ecosystem: maven
  directory: "/lang/"
  schedule:
    interval: daily
  commit-message:
    prefix: "Maven"
    include: "scope"
  groups:
    junit:
      patterns:
      - "org.junit.*"
    xtext:
      patterns:
      - "org.eclipse.xtext:org.eclipse.xtext:*"